acceptable_char_diff: 3
acceptable_diff: 0
candidates: 1
cvvp_amount: 0.0
diffusion_temperature: 1.0
latent_averaging_mode: Tortoise original (bad)
length_penalty: 6.0
long_break_val: 3000
low_vram: false
max_mel_tokens: 500
max_self_correcting_rounds: 3
output_path: results/
preset: ultra_fast
repetition_penalty: 8.0
sampler: ddim
seed: 0
select_ar_checkpoint: autoregressive.pth
short_break_val: 500
split_length: long
steps: 30
temperature: 1.0
text: Insert your text here for your audio book, or use the file selector option above
  this field. Many thanks to the original creators of Tortoise text-to-speech and
  the creators of Tortoise fast repository. My lifelong dream has finally come true
  in this project!
top_p: 0.8
voice: kathleen01
voice_fixer: true
